# Generated by Django 4.0 on 2021-12-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='gallery/gallery-1.jpg', null=True, upload_to='images'),
        ),
    ]
