# Generated by Django 4.0 on 2022-01-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_service_skill_alter_project_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
